version: '3.8'

services:
  # Redpanda Service
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.11
    container_name: redpanda
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    environment:
      REDPANDA_MODE: dev-container
      REDPANDA_LOG_LEVEL: error

  # Topic Creator Service
  topic-creator:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.11
    container_name: topic-creator
    volumes:
      - ./create-topics-redpanda.sh:/create-topics.sh
    depends_on:
      - redpanda
    entrypoint: ["/bin/sh"]
    command: ["-c", "echo 'Waiting for Redpanda to be ready...'; while ! nc -z redpanda 9092; do echo 'Port not ready yet...'; sleep 2; done; echo 'Port is ready, checking cluster...'; until rpk cluster info --brokers=redpanda:9092 > /dev/null 2>&1; do echo 'Cluster not ready yet...'; sleep 2; done; echo 'Redpanda is ready!'; /create-topics.sh"]

volumes:
  redpanda_data:

networks:
  kafka-network:
    driver: bridge