version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - platform_kafka-network
    environment:
      - BROKER_TYPE=confluent
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - POSTGRES_HOST=timescaledb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iot_platform
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - platform_kafka-network
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  platform_kafka-network:
    external: true 