FROM confluentinc/cp-server-connect:7.5.0

USER root
RUN microdnf update && microdnf install -y curl jq && microdnf clean all

WORKDIR /app

COPY scripts/manage-connectors.sh .
RUN chmod +x manage-connectors.sh

ENTRYPOINT ["/app/manage-connectors.sh"] 